### PR TITLE
Expand location metadata

### PR DESCRIPTION
**Pull request by connyay**

### CODE REVIEW

**Comment by connyay** [comment]
alternative to https://github.com/zonedb/zonedb/pull/364

More readable, but a breaking change 😦

**Comment by cee-dub** [comment]
Let's make this backwards compatible: the text format of the database is less important, but the changes to `zone.go` should be changed to be additive, rather than breaking.

**Comment by cee-dub** [comment]
Considerations for downstream clients of this code: changing a `[]string` to a `struct`, changing the name of an exported struct field from `Locations` to `Location`.

**Comment by cee-dub** [comment]
To avoid having any downstream libraries consume the `build` package, we should take advantage of the (`internal` package mechanism)[https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit].

**Pull request closed without merging**
