### PR TITLE
Update lol gTLD RDAP address in tests

### PR DESCRIPTION
**Pull request by tbregolin**
CentralNic submitted the new records earlier this week, and the IANA DB
has been updated.

### CODE REVIEW

**Comment by case** [comment]
Thanks @tbregolin!

**Comment by case** [comment]
@tbregolin I think what you'll need to do here is:

1. Update the `rdapURLs` value in `metadata/lol.json` with the new CentralNic URL
2. Run `make normalize` (which will run `go generate` and update the root `zones.go` file)
3. Run the tests again, which should pass.
4. Commit these changes to your branch

**Comment by tbregolin** [comment]
@case thank you and my apologies -- I didn't realize the tests had passed locally only because my working tree was dirty form a previous local update. Updated.

**Comment by case** [comment]
No worries, the documentation and tooling for this workflow is probably a bit confusing.

Feel free to update the Readme from your experience, if that would have made contributing more straightforward — we appreciate your contribution here!

**Comment by case** [comment]
Looks like the nightly update job picked up the changes for the other Uniregistry -> CentralNic zones:

https://github.com/zonedb/zonedb/commit/b73642925fcdea4409901f560a0bc776496fcc59

**Pull request merged**
