### PR TITLE
Omit test run in update target

### PR DESCRIPTION
**Pull request by cee-dub**

### CODE REVIEW

**Review by ydnar — CHANGES_REQUESTED** [review]
I think it’s OK to split `test` out of `update`, but GitHub Actions should absolutely run the tests before committing to `main`.

We don’t need a separate `ci-update` step. A simple `update` that doesn’t run tests is fine, so the GHA config can have a separate `test` step.

**Comment by cee-dub** [comment]
It does run the tests in the action workflow. Twice, before this change

**Comment by cee-dub** [comment]
Separately, the update task is breaking the tests by adding whoisURLs where they aren't needed. That's what your help was requested for.

**Comment by cee-dub** [comment]
Superseded by #819

**Pull request closed without merging**
